### ISSUE TITLE
xbmgmt ERROR after flash update

### ISSUE THREAD

**Issue by shaunclimbon** [Xilinx/video-sdk#42] opened 2022-08-25 18:35 UTC
Installing SDK and flashing cards on a supported env (Ubuntu 18.04 w/ 5.4 kernel).  Install script ran fine and card update seemed fine as well but after a cold re-boot xbmgmt gives the following strange error (indicating a Windows path):

[xbmgmt] ERROR: boost::filesystem::status: Permission denied: "C:\Xilinx"

Full log is below.  Note that card passes validation despite this error.

 ```
$ sudo /opt/xilinx/xrt/bin/xball --device-filter u30 xbmgmt program --base
Discovering installed devices....
Skip: xilinx_u250_gen3x16_base_1
Skip: xilinx_u200_xdma_201830_2
Match: xilinx_u30_gen3x4_base_2
Match: xilinx_u30_gen3x4_base_2


=====================================================================
1 / 2 [0000:8a:00.0] : xilinx_u30_gen3x4_base_2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Command: /opt/xilinx/xrt/bin/xbmgmt program --base --device 0000:8a:00.0

XRT build version: 2.11.691
Build hash: 3e695ed86d15164e36267fb83def6ff2aaecd758
Build date: 2021-11-18 18:16:39
Git branch: 2021.1
PID: 3680
UID: 0
[Wed Aug 24 22:11:20 2022 GMT]
HOST: xowalveoaccel40
EXE: /opt/xilinx/xrt/bin/unwrapped/xbmgmt2
[xbmgmt] ERROR: boost::filesystem::status: Permission denied: "C:\Xilinx"

Command Return Value: 256 [Error(s) occured]


=====================================================================
2 / 2 [0000:89:00.0] : xilinx_u30_gen3x4_base_2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Command: /opt/xilinx/xrt/bin/xbmgmt program --base --device 0000:89:00.0

XRT build version: 2.11.691
Build hash: 3e695ed86d15164e36267fb83def6ff2aaecd758
Build date: 2021-11-18 18:16:39
Git branch: 2021.1
PID: 3707
UID: 0
[Wed Aug 24 22:11:21 2022 GMT]
HOST: xowalveoaccel40
EXE: /opt/xilinx/xrt/bin/unwrapped/xbmgmt2
[xbmgmt] ERROR: boost::filesystem::status: Permission denied: "C:\Xilinx"

Command Return Value: 256 [Error(s) occured]


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Summary:
   Installed device(s) : 4
          Shell Filter : 'u30'
      Number Evaluated : 2
                Passed : 0
                Failed : 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Validation log (with warning about SC version):
```
sudo /opt/xilinx/xrm/tools/stop_xrmd.sh
xball --device-filter u30 xbutil validate
Discovering installed devices....
Skip: xilinx_u250_gen3x16_base_1
Skip: xilinx_u200_xdma_201830_2
Match: xilinx_u30_gen3x4_base_2
Match: xilinx_u30_gen3x4_base_2


=====================================================================
1 / 2 [0000:8a:00.1] : xilinx_u30_gen3x4_base_2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Command: /opt/xilinx/xrt/bin/xbutil validate --device 0000:8a:00.1

Starting validation for 1 devices

Validate Device           : [0000:8a:00.1]
    Platform              : xilinx_u30_gen3x4_base_2
    SC Version            : 6.3.7
    Platform ID           : 0x0
-------------------------------------------------------------------------------
Test 1 [0000:8a:00.1]     : PCIE link
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 2 [0000:8a:00.1]     : SC version
    Warning(s)            : SC firmware mismatch
                            SC firmware version 6.3.7 is running on the board, but SC
                            firmware version 6.3.8 is expected from the installed
                            shell. Please use xbmgmt examine to check the installed
                            shell.
    Test Status           : [PASSED WITH WARNINGS]
-------------------------------------------------------------------------------
Test 3 [0000:8a:00.1]     : Verify kernel
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 4 [0000:8a:00.1]     : DMA
    Details               : Host -> PCIe -> FPGA write bandwidth = 3297.577376 MB/s
                            Host <- PCIe <- FPGA read bandwidth = 2973.874052 MB/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 5 [0000:8a:00.1]     : iops
    Details               : IOPS: 111588 (verify)
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 6 [0000:8a:00.1]     : Bandwidth kernel
    Details               : Maximum throughput: 8843.94MB/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 7 [0000:8a:00.1]     : vcu
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed, but with warnings. Please run the command '--verbose' option for more details

Validation Summary
------------------
1  device(s) evaluated
1  device(s) validated successfully
0  device(s) had exceptions during validation

Validated successfully [1 device(s)]
  - [0000:8a:00.1] : xilinx_u30_gen3x4_base_2

Validation Exceptions [0 device(s)]

Warnings produced during test [1 device(s)] (Note: The given test successfully validated)
  - [0000:8a:00.1] : xilinx_u30_gen3x4_base_2  : Test(s): 'SC version'

Command Return Value: 0 [Operation successful]


=====================================================================
2 / 2 [0000:89:00.1] : xilinx_u30_gen3x4_base_2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Command: /opt/xilinx/xrt/bin/xbutil validate --device 0000:89:00.1

Starting validation for 1 devices

Validate Device           : [0000:89:00.1]
    Platform              : xilinx_u30_gen3x4_base_2
    SC Version            : 6.3.7
    Platform ID           : 0x0
-------------------------------------------------------------------------------
Test 1 [0000:89:00.1]     : PCIE link
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 2 [0000:89:00.1]     : SC version
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 3 [0000:89:00.1]     : Verify kernel
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 4 [0000:89:00.1]     : DMA
    Details               : Host -> PCIe -> FPGA write bandwidth = 3325.225930 MB/s
                            Host <- PCIe <- FPGA read bandwidth = 2870.099949 MB/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 5 [0000:89:00.1]     : iops
    Details               : IOPS: 110820 (verify)
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 6 [0000:89:00.1]     : Bandwidth kernel
    Details               : Maximum throughput: 8844.2MB/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 7 [0000:89:00.1]     : vcu
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed. Please run the command '--verbose' option for more details

Validation Summary
------------------
1  device(s) evaluated
1  device(s) validated successfully
0  device(s) had exceptions during validation

Validated successfully [1 device(s)]
  - [0000:89:00.1] : xilinx_u30_gen3x4_base_2

Validation Exceptions [0 device(s)]

Warnings produced during test [0 device(s)] (Note: The given test successfully validated)

Command Return Value: 0 [Operation successful]


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Summary:
   Installed device(s) : 4
          Shell Filter : 'u30'
      Number Evaluated : 2
                Passed : 2
                Failed : 0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by ThomasXilinx** [comment] 2022-08-26 20:29
This is a known issue which has already been fixed in a newer version of XRT: https://github.com/Xilinx/XRT/commit/aa67c81332cd755551d527452ae63c2af80b67ab
One possibility to move past the issue is to install a newer version of XRT in order to flash the cards, and then revert to the version of XRT included in the Video SDK to run your workloads.

**Closed as completed by ThomasXilinx** 2022-08-26 20:29 UTC

**Comment by shaunclimbon** [comment] 2022-08-30 22:17
Thanks for the feedback.  I was also able to work-around it by using the Docker image.
